export * from './LandingPage'
export * from './IdentityPage'
export * from './CovidQuestionnairePage'
export * from './VaccinationPage'
export * from './TipsPage'
export * from './ThankYouPage'
export * from './NotFoundPage'
