export { default as CovidQuestionnairePageSvg } from './CovidQuestionnairePageSvg'
export { default as IdentityPageNumberSvg } from './IdentityPageNumberSvg'
export { default as RedberrySvg } from './RedberrySvg'
export { default as LeftArrow } from './LeftArrow'
export { default as RightArrow } from './RightArrow'
export { default as TipsPageNumberSvg } from './TipsPageNumberSvg'
export { default as VaccinationPageNumberSvg } from './VaccinationPageNumberSvg'
